version: '3.1'

services:
    postgres:   
        image: postgres
        ports:
            - 5438:5432
        environment:
            POSTGRES_DB: dost_db
            POSTGRES_USER: dost_user
            POSTGRES_PASSWORD: password
        volumes:
            - ../pgdb/:/var/lib/postgresql/data

    redis:
        image: redis
        ports:
            - '127.0.0.1:6379:6379'
        restart: always


