# Generated by Django 2.2.16 on 2021-10-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=250, verbose_name='Position')),
                ('position_info', models.TextField(verbose_name='Position info')),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('secret_key', models.CharField(max_length=2500, verbose_name='Secret Key')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consumer',
                'verbose_name_plural': 'Consumers',
            },
        ),
    ]
