# Generated by Django 2.2.16 on 2021-10-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='secret_key',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Secret Key'),
        ),
    ]
